spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/admin_shipping_mgr
    username: admin_shipping_mgr
    password: Admin@1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
      show-sql: true
      hibernate:
       dialect: MySQL8Dialect
       naming-strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
       ddl-auto: none
  server:
      port: 80
websiteUrl: https://mystore.com