spring:
  application:
    name: shipping-mgr
  liquibase:
        enabled: false
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 15m
    refreshTokenExpiration: 604800 # 7d
  profiles:
    active: dev