name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Stop existing app (adjust as needed)
            sudo systemctl stop springbootapp || true

            # Copy new JAR to deployment folder
            cp /root/shipping-mgr.jar /root/shipping-mgr.jar.bak
            mv /tmp/shipping-mgr.jar /root/shipping-mgr.jar

            # Start app
            sudo systemctl start springbootapp
